def load_controller():
    import src.main.controller.account
    import src.main.controller.role
    import src.main.controller.staff
    import src.main.controller.proposal_author
    import src.main.controller.project
    import src.main.controller.project_category
    import src.main.controller.comment
    import src.main.controller.student
    import src.main.controller.email_log
