"""Project_id renamed in Comment table

Revision ID: 105184dbe2a1
Revises: 0d23218b9953
Create Date: 2020-04-26 16:51:34.067499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '105184dbe2a1'
down_revision = '0d23218b9953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('project', sa.Integer(), nullable=False))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'project', ['project'], ['id'])
    op.drop_column('comment', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'project', ['project_id'], ['id'])
    op.drop_column('comment', 'project')
    # ### end Alembic commands ###
