"""more fields added in Project table

Revision ID: 224e95c9a226
Revises: 83e4eae0fa93
Create Date: 2020-04-28 13:44:29.059294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224e95c9a226'
down_revision = '83e4eae0fa93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('availability', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'availability')
    # ### end Alembic commands ###
