"""Added project in email_log table

Revision ID: 29fee6d49079
Revises: 25c97f4ad04e
Create Date: 2020-05-30 17:57:19.318929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fee6d49079'
down_revision = '25c97f4ad04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_log', sa.Column('project', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'email_log', 'project', ['project'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_log', type_='foreignkey')
    op.drop_column('email_log', 'project')
    # ### end Alembic commands ###
