"""platform field added in Project table

Revision ID: 83e4eae0fa93
Revises: ede6af01474a
Create Date: 2020-04-28 13:36:33.784246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e4eae0fa93'
down_revision = 'ede6af01474a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('platform', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'platform')
    # ### end Alembic commands ###
