"""Added student in comment table

Revision ID: 8640811f2121
Revises: 28f6e9f3c924
Create Date: 2020-05-16 15:41:28.324040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8640811f2121'
down_revision = '28f6e9f3c924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('student', sa.Integer(), nullable=True))
    op.alter_column('comment', 'project',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'comment', 'student', ['student'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'project',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('comment', 'student')
    # ### end Alembic commands ###
