"""more fields added in Project table

Revision ID: ede6af01474a
Revises: 0d23218b9953
Create Date: 2020-04-28 13:25:43.897827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ede6af01474a'
down_revision = '0d23218b9953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('project', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'deadline')
    op.drop_column('project', 'country')
    op.drop_column('project', 'city')
    # ### end Alembic commands ###
